[COLORS] - atualizando o foundation
ditointernet/careers-page pull request #45
Opened 2023-08-28 18:43 UTC by KaioMaiaDito

Trocando todas as cores da versão do foundation 1.0 para as cores da versão 1.6 e fazendo alguns ajustes no TYPOGRAPHY para que o código não quebre

2023-08-28 18:53 UTC, LucasMonteiroDito approved these changes

2023-08-28 20:30 UTC, UriellVianaDito requested changes
só um ajuste

2023-08-28 22:15 UTC, UriellVianaDito approved these changes
cr ok!

2023-08-29 14:23 UTC, MarcosLottDito approved these changes

2023-09-12 18:52 UTC, merged